var user = {
login: "AlexandriaLewis",
id: 15950907,
avatar_url: "https://avatars.githubusercontent.com/u/15950907?v=3",
gravatar_id: "",
url: "https://api.github.com/users/AlexandriaLewis",
html_url: "https://github.com/AlexandriaLewis",
followers_url: "https://api.github.com/users/AlexandriaLewis/followers",
following_url: "https://api.github.com/users/AlexandriaLewis/following{/other_user}",
gists_url: "https://api.github.com/users/AlexandriaLewis/gists{/gist_id}",
starred_url: "https://api.github.com/users/AlexandriaLewis/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/AlexandriaLewis/subscriptions",
organizations_url: "https://api.github.com/users/AlexandriaLewis/orgs",
repos_url: "https://api.github.com/users/AlexandriaLewis/repos",
events_url: "https://api.github.com/users/AlexandriaLewis/events{/privacy}",
received_events_url: "https://api.github.com/users/AlexandriaLewis/received_events",
type: "User",
site_admin: false,
name: "Alexandria Lewis",
company: null,
blog: null,
location: "South Carolina",
email: null,
hireable: null,
bio: null,
public_repos: 12,
public_gists: 0,
followers: 0,
following: 0,
created_at: "2015-11-21T01:21:59Z",
updated_at: "2016-02-17T00:38:11Z"
}
